# Servlet Container & Health Setup
server:
  address: 0.0.0.0
  port: 8980
management:
  endpoints:
    enabled: false
    health:
      enabled: true

# Camel Spring Boot
camel:
  springboot:
    name: camel-splitter

# Logging
logging:
  config: classpath:logback.xml
  level:
    com.redhat.examples: INFO
    
# Application
splitter:
  dir: target/input/
  outDir: target/output/
