# Servlet Container & Health Setup
server:
  address: 0.0.0.0
  port: 9981
management:
  endpoints:
    enabled: false
    health:
      enabled: true

# AMQPHub
amqphub:
  amqp10jms:
    pool:
      enabled: true
    remote-url: amqp://localhost:5672
    #username: admin
    #password: admin

# Camel Spring Boot
camel:
  springboot:
    name: camel-aggregator

# Logging
logging:
  config: classpath:logback.xml
  level:
    com.redhat.examples: INFO
    
# Application
aggregator:
  dir: target/output/
