# Servlet Container & Health Setup
server:
  address: 0.0.0.0
  port: 9980
management:
  endpoints:
    enabled: false
    health:
      enabled: true

# Camel Spring Boot
camel:
  springboot:
    name: camel-processor

# Logging
logging:
  config: classpath:logback.xml
  level:
    com.redhat.examples: INFO

splitter:
  inDir: /Users/svalluru/tmp/josh_demo/camel-orders-demo/camel-splitter/target/output
  outDir: /target/output
